### ISSUE TITLE
Cannot update on 4.3.0. - Compile error

### ISSUE THREAD

**Issue by ric-osorio** [RfastOfficial/Rfast#93] opened 2023-12-30 13:13 UTC
**Describe the bug**
When updating to the latest github version on CentOS, it doesn't compile due to missing import of execution.

* installing *source* package ‘Rfast’ ...
** package ‘Rfast’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)’
using C++ compiler: ‘g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)’
using C++17
g++ -std=gnu++17 -I"/opt/R/4.3.0/lib/R/include" -DNDEBUG -I../inst/include -I'/home/byspectra/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include' -I'/home/byspectra/R/x86_64-pc-linux-gnu-library/4.3/RcppArmadillo/include' -I'/home/byspectra/R/x86_64-pc-linux-gnu-library/4.3/RcppParallel/include' -I/usr/local/include   -fopenmp -fpic  -g -O2  -c Coeff.cpp -o Coeff.o
In file included from ../inst/include/Rfast/templates.h:10,
                 from ../inst/include/Rfast/matrix.hpp:14,
                 from ../inst/include/Rfast.h:5,
                 from mn.h:4,
                 from Coeff.cpp:4:
../inst/include/Rfast/parallel.h:20:10: fatal error: execution: No such file or directory
 #include <execution>
          ^~~~~~~~~~~
compilation terminated.

**To Reproduce**
1. Using CentOS or Almalinux, instaling R 4.3.0.:

library(devtools)
devtools:: install_github("RfastOfficial/Rfast")

**Expected behavior**
Should compile

**Desktop (please complete the following information):**
 - OS: CentOS
 - R-Version 4.3.0.
 - Rfast-Version Latest

**Comment by grst** [comment] 2024-01-02 14:18
Same here with Centos 7 and R 4.3.2

**Comment by ManosPapadakis95** [comment] 2024-01-03 12:03
This issue is a duplicate of #92. Please continue the discussion on the original issue: #92

**Closed** 2024-01-03 12:03 UTC
Labels: bug
